trainer_config:
  target_namespace: "default"
  save_with_id: true
  output_dir: /data/output
  tuning_image: sft-trainer
  image_pull_secrets: all-icr-io
  # Default resource allocation for a job, if unspecified
  default_resources:
    cpu: 1
    gpu: 0
  # How often full reconciles should run, in seconds
  reconcile_interval: 30
  # Time limit on job runs, in seconds. If >0, job will be terminated if not completed in time.
  job_time_limit: 28800
training_volumes:
  - name: input-data
    pvc_name: cos-ray-test
    mount_path: /data/input
  - name: output-data
    pvc_name: cos-ray-output
    mount_path: /data/output
datastore:
  type: redis
  helper_class: RedisHelper
  helper_module_path: train_conductor.datastore.redis
  connection:
    host: localhost
    port: 6379
    db_num: 0
    user: ""