trainer_type: K8S_JOB_TRAIN
import_class: train_conductor.modules.k8s_backend.K8sJobTrainModule
trainer_config:
  target_namespace: "fmaas-dev"
  save_with_id: true
  output_dir: /data/output
  base_model_path: /data/
  tuning_image: us.icr.io/cil15-shared-registry/sft-trainer:011224
  image_pull_secrets: all-icr-io
  # Default resource allocation for a job, if unspecified
  default_resources:
    cpu: 1
    gpu: 1
  # How often full reconciles should run, in seconds
  reconcile_interval: 30
  # Time limit on job runs, in seconds. If >0, job will be terminated if not completed in time.
  job_time_limit: 28800
training_volumes:
  - name: models
    pvc_name: fmaas-model-pvc
    mount_path: /data/models
  - name: input-data
    pvc_name: cos-ray-test
    mount_path: /data/input
  - name: output-data
    pvc_name: cos-ray-output
    mount_path: /data/output
datastore:
  type: redis
  helper_class: RedisHelper
  helper_module_path: train_conductor.datastore.redis
  connection:
    host: localhost
    port: 6379
    db_num: 0
    user: ""