apiVersion: v1
kind: ServiceAccount
metadata:
  name: train-conductor

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: train-conductor-role
rules:
- apiGroups: ["batch", ""]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete", "patch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: train-conductor-role-binding
subjects:
- kind: ServiceAccount
  name: train-conductor
roleRef:
  kind: Role
  name: train-conductor-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-conductor-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-conductor
  template:
    metadata:
      labels:
        app: train-conductor
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: train-conductor-config
      containers:
      - name: train-conductor
        image: localhost/train-conductor:latest
        imagePullPolicy: Never
        env:
        - name: RUNTIME_CONFIG_FILE
          value: /etc/config/config.yaml
        - name: DISABLE_WATCHER
          value: "true"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-conductor-watcher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-conductor-watcher
  template:
    metadata:
      labels:
        app: train-conductor-watcher
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: train-conductor-config
      serviceAccountName: train-conductor
      containers:
      - name: train-conductor
        image: localhost/train-conductor:latest
        imagePullPolicy: Never
        env:
        - name: RUNTIME_CONFIG_FILE
          value: /etc/config/config.yaml
        - name: DISABLE_GRPC
          value: "true"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-conductor-redis
  template:
    metadata:
      labels:
        app: train-conductor-redis
    spec:
      volumes:
        - name: redis-storage
          emptyDir: {}
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: "/data"
            name: redis-storage

---
apiVersion: v1
kind: Service
metadata:
  name: train-conductor-service
spec:
  selector:
    app: train-conductor
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: train-conductor-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
